# Generated by Django 5.0.4 on 2024-05-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gear',
            field=models.IntegerField(choices=[(0, 'manuel'), (1, 'auto'), (2, 'semi-auto')], null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='seat',
            field=models.SmallIntegerField(null=True),
        ),
    ]
