# Generated by Django 5.0.4 on 2024-05-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_gear_item_rating_item_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fuel_type',
            field=models.IntegerField(choices=[(0, 'diesel'), (1, 'motorin'), (2, 'hybrid'), (3, 'electric')], null=True),
        ),
    ]
